/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { TblHistoriaClinica } from '../model/tblHistoriaClinica';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class HistoriaClinicaControllerService {

    protected basePath = '//env-9292028.jelastic.saveincloud.net/';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * getHistoriaClinica
     * 
     * @param idHistoriaClinica idHistoriaClinica
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getHistoriaClinicaUsingGET(idHistoriaClinica?: number, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public getHistoriaClinicaUsingGET(idHistoriaClinica?: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public getHistoriaClinicaUsingGET(idHistoriaClinica?: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public getHistoriaClinicaUsingGET(idHistoriaClinica?: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {


        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (idHistoriaClinica !== undefined && idHistoriaClinica !== null) {
            queryParameters = queryParameters.set('idHistoriaClinica', <any>idHistoriaClinica);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<any>('get',`${this.basePath}/historiaClinica/get`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * getHistoriaClinicabyPacienteandByDepartamento
     * 
     * @param cedula cedula
     * @param idDepartamento idDepartamento
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getHistoriaClinicabyPacienteandByDepartamentoUsingGET(cedula?: string, idDepartamento?: number, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public getHistoriaClinicabyPacienteandByDepartamentoUsingGET(cedula?: string, idDepartamento?: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public getHistoriaClinicabyPacienteandByDepartamentoUsingGET(cedula?: string, idDepartamento?: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public getHistoriaClinicabyPacienteandByDepartamentoUsingGET(cedula?: string, idDepartamento?: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {



        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (cedula !== undefined && cedula !== null) {
            queryParameters = queryParameters.set('cedula', <any>cedula);
        }
        if (idDepartamento !== undefined && idDepartamento !== null) {
            queryParameters = queryParameters.set('idDepartamento', <any>idDepartamento);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<any>('get',`${this.basePath}/historiaClinica/getHistoriaClinicabyCedulaandDepartamento`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * listHistoriaClinicaByCedula
     * 
     * @param cedula cedula
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public listHistoriaClinicaByCedulaUsingGET(cedula?: string, observe?: 'body', reportProgress?: boolean): Observable<Array<TblHistoriaClinica>>;
    public listHistoriaClinicaByCedulaUsingGET(cedula?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<TblHistoriaClinica>>>;
    public listHistoriaClinicaByCedulaUsingGET(cedula?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<TblHistoriaClinica>>>;
    public listHistoriaClinicaByCedulaUsingGET(cedula?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {


        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (cedula !== undefined && cedula !== null) {
            queryParameters = queryParameters.set('cedula', <any>cedula);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<TblHistoriaClinica>>('get',`${this.basePath}/historiaClinica/listHistoriaClinicabyCedula`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * listHistoriaClinicaFindAll
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public listHistoriaClinicaFindAllUsingGET(observe?: 'body', reportProgress?: boolean): Observable<any>;
    public listHistoriaClinicaFindAllUsingGET(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public listHistoriaClinicaFindAllUsingGET(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public listHistoriaClinicaFindAllUsingGET(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<any>('get',`${this.basePath}/historiaClinica/list`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * listHistoriaClinica
     * 
     * @param idDepartamento idDepartamento
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public listHistoriaClinicaUsingGET(idDepartamento?: number, observe?: 'body', reportProgress?: boolean): Observable<Array<TblHistoriaClinica>>;
    public listHistoriaClinicaUsingGET(idDepartamento?: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<TblHistoriaClinica>>>;
    public listHistoriaClinicaUsingGET(idDepartamento?: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<TblHistoriaClinica>>>;
    public listHistoriaClinicaUsingGET(idDepartamento?: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {


        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (idDepartamento !== undefined && idDepartamento !== null) {
            queryParameters = queryParameters.set('idDepartamento', <any>idDepartamento);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<TblHistoriaClinica>>('get',`${this.basePath}/historiaClinica/listHistoriaClinica`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * post
     * 
     * @param fechaApertura fechaApertura
     * @param idDepartamento idDepartamento
     * @param idPaciente idPaciente
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public postUsingPOST(fechaApertura?: string, idDepartamento?: number, idPaciente?: number, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public postUsingPOST(fechaApertura?: string, idDepartamento?: number, idPaciente?: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public postUsingPOST(fechaApertura?: string, idDepartamento?: number, idPaciente?: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public postUsingPOST(fechaApertura?: string, idDepartamento?: number, idPaciente?: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {




        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (fechaApertura !== undefined && fechaApertura !== null) {
            queryParameters = queryParameters.set('fechaApertura', <any>fechaApertura);
        }
        if (idDepartamento !== undefined && idDepartamento !== null) {
            queryParameters = queryParameters.set('idDepartamento', <any>idDepartamento);
        }
        if (idPaciente !== undefined && idPaciente !== null) {
            queryParameters = queryParameters.set('idPaciente', <any>idPaciente);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<any>('post',`${this.basePath}/historiaClinica/post`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
