/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';


import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class PacienteControllerService {

    protected basePath = '//env-9292028.jelastic.saveincloud.net/';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * actualizarPaciente
     * 
     * @param apellido apellido
     * @param cedula cedula
     * @param correo correo
     * @param direccion direccion
     * @param fechaNacimiento fechaNacimiento
     * @param nombre nombre
     * @param pacDiscapacidad pacDiscapacidad
     * @param telefono telefono
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public actualizarPacienteUsingPUT(apellido?: string, cedula?: string, correo?: string, direccion?: string, fechaNacimiento?: string, nombre?: string, pacDiscapacidad?: string, telefono?: string, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public actualizarPacienteUsingPUT(apellido?: string, cedula?: string, correo?: string, direccion?: string, fechaNacimiento?: string, nombre?: string, pacDiscapacidad?: string, telefono?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public actualizarPacienteUsingPUT(apellido?: string, cedula?: string, correo?: string, direccion?: string, fechaNacimiento?: string, nombre?: string, pacDiscapacidad?: string, telefono?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public actualizarPacienteUsingPUT(apellido?: string, cedula?: string, correo?: string, direccion?: string, fechaNacimiento?: string, nombre?: string, pacDiscapacidad?: string, telefono?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {









        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (apellido !== undefined && apellido !== null) {
            queryParameters = queryParameters.set('apellido', <any>apellido);
        }
        if (cedula !== undefined && cedula !== null) {
            queryParameters = queryParameters.set('cedula', <any>cedula);
        }
        if (correo !== undefined && correo !== null) {
            queryParameters = queryParameters.set('correo', <any>correo);
        }
        if (direccion !== undefined && direccion !== null) {
            queryParameters = queryParameters.set('direccion', <any>direccion);
        }
        if (fechaNacimiento !== undefined && fechaNacimiento !== null) {
            queryParameters = queryParameters.set('fechaNacimiento', <any>fechaNacimiento);
        }
        if (nombre !== undefined && nombre !== null) {
            queryParameters = queryParameters.set('nombre', <any>nombre);
        }
        if (pacDiscapacidad !== undefined && pacDiscapacidad !== null) {
            queryParameters = queryParameters.set('pacDiscapacidad', <any>pacDiscapacidad);
        }
        if (telefono !== undefined && telefono !== null) {
            queryParameters = queryParameters.set('telefono', <any>telefono);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<any>('put',`${this.basePath}/paciente/put`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * listPaciente
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public listPacienteUsingGET(observe?: 'body', reportProgress?: boolean): Observable<any>;
    public listPacienteUsingGET(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public listPacienteUsingGET(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public listPacienteUsingGET(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<any>('get',`${this.basePath}/paciente/list`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * listPaciente
     * 
     * @param estadoPaciente estadoPaciente
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public listPacienteUsingGET1(estadoPaciente?: boolean, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public listPacienteUsingGET1(estadoPaciente?: boolean, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public listPacienteUsingGET1(estadoPaciente?: boolean, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public listPacienteUsingGET1(estadoPaciente?: boolean, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {


        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (estadoPaciente !== undefined && estadoPaciente !== null) {
            queryParameters = queryParameters.set('estadoPaciente', <any>estadoPaciente);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<any>('get',`${this.basePath}/paciente/lista`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * pacientePersona
     * 
     * @param cedula cedula
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public pacientePersonaUsingGET(cedula?: string, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public pacientePersonaUsingGET(cedula?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public pacientePersonaUsingGET(cedula?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public pacientePersonaUsingGET(cedula?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {


        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (cedula !== undefined && cedula !== null) {
            queryParameters = queryParameters.set('cedula', <any>cedula);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<any>('get',`${this.basePath}/paciente/pacientePersona`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * pacientesByID
     * 
     * @param idPaciente idPaciente
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public pacientesByIDUsingGET(idPaciente?: number, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public pacientesByIDUsingGET(idPaciente?: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public pacientesByIDUsingGET(idPaciente?: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public pacientesByIDUsingGET(idPaciente?: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {


        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (idPaciente !== undefined && idPaciente !== null) {
            queryParameters = queryParameters.set('idPaciente', <any>idPaciente);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<any>('get',`${this.basePath}/paciente/pacientesByID`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * postPaciente
     * 
     * @param apellido apellido
     * @param cedula cedula
     * @param correo correo
     * @param direccion direccion
     * @param fechaNacimiento fechaNacimiento
     * @param nombre nombre
     * @param pacDiscapacidad pacDiscapacidad
     * @param telefono telefono
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public postPacienteUsingPOST(apellido?: string, cedula?: string, correo?: string, direccion?: string, fechaNacimiento?: string, nombre?: string, pacDiscapacidad?: string, telefono?: string, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public postPacienteUsingPOST(apellido?: string, cedula?: string, correo?: string, direccion?: string, fechaNacimiento?: string, nombre?: string, pacDiscapacidad?: string, telefono?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public postPacienteUsingPOST(apellido?: string, cedula?: string, correo?: string, direccion?: string, fechaNacimiento?: string, nombre?: string, pacDiscapacidad?: string, telefono?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public postPacienteUsingPOST(apellido?: string, cedula?: string, correo?: string, direccion?: string, fechaNacimiento?: string, nombre?: string, pacDiscapacidad?: string, telefono?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {









        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (apellido !== undefined && apellido !== null) {
            queryParameters = queryParameters.set('apellido', <any>apellido);
        }
        if (cedula !== undefined && cedula !== null) {
            queryParameters = queryParameters.set('cedula', <any>cedula);
        }
        if (correo !== undefined && correo !== null) {
            queryParameters = queryParameters.set('correo', <any>correo);
        }
        if (direccion !== undefined && direccion !== null) {
            queryParameters = queryParameters.set('direccion', <any>direccion);
        }
        if (fechaNacimiento !== undefined && fechaNacimiento !== null) {
            queryParameters = queryParameters.set('fechaNacimiento', <any>fechaNacimiento);
        }
        if (nombre !== undefined && nombre !== null) {
            queryParameters = queryParameters.set('nombre', <any>nombre);
        }
        if (pacDiscapacidad !== undefined && pacDiscapacidad !== null) {
            queryParameters = queryParameters.set('pacDiscapacidad', <any>pacDiscapacidad);
        }
        if (telefono !== undefined && telefono !== null) {
            queryParameters = queryParameters.set('telefono', <any>telefono);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<any>('post',`${this.basePath}/paciente/post`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * updatePacienteInactivo
     * 
     * @param cedula cedula
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public updatePacienteInactivoUsingPUT(cedula?: string, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public updatePacienteInactivoUsingPUT(cedula?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public updatePacienteInactivoUsingPUT(cedula?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public updatePacienteInactivoUsingPUT(cedula?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {


        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (cedula !== undefined && cedula !== null) {
            queryParameters = queryParameters.set('cedula', <any>cedula);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<any>('put',`${this.basePath}/paciente/updatePacienteInactivo`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
